"""
OpenRouter API service — handles all communication with the LLM.
Used for NL2SQL generation and business answer synthesis.

OpenRouter is a unified gateway for multiple LLM providers.
Docs: https://openrouter.ai/docs
"""

import httpx
import logging
from typing import Optional
from app.config import get_settings

logger = logging.getLogger(__name__)

# OpenRouter API endpoint
OPENROUTER_API_URL = "https://openrouter.ai/api/v1/chat/completions"


class OpenRouterError(Exception):
    """Custom exception for OpenRouter API failures."""

    def __init__(self, message: str, status_code: Optional[int] = None):
        self.message = message
        self.status_code = status_code
        super().__init__(self.message)


async def call_llm(
    system_prompt: str,
    user_message: str,
    temperature: float = 0.1,
    max_tokens: int = 1000,
) -> str:
    """
    Send a prompt to OpenRouter and return the LLM's text response.

    Args:
        system_prompt: Instructions/context for the LLM (schema, rules, etc.)
        user_message: The user's question or request
        temperature: Randomness (0.0 = deterministic, 1.0 = creative)
        max_tokens: Maximum response length

    Returns:
        The LLM's text response as a string

    Raises:
        OpenRouterError: If the API call fails or returns an error
    """
    settings = get_settings()

    if not settings.openrouter_api_key:
        raise OpenRouterError(
            "OpenRouter API key is not configured. Set OPENROUTER_API_KEY in .env",
            status_code=500,
        )

    headers = {
        "Authorization": f"Bearer {settings.openrouter_api_key}",
        "Content-Type": "application/json",
        "HTTP-Referer": "https://wfx-ai-erp.vercel.app",
        "X-Title": "WFX AI ERP",
    }

    payload = {
        "model": settings.openrouter_model,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_message},
        ],
        "temperature": temperature,
        "max_tokens": max_tokens,
        "top_p": 0.9,
    }

    try:
        async with httpx.AsyncClient(timeout=30.0) as client:
            response = await client.post(
                OPENROUTER_API_URL,
                json=payload,
                headers=headers,
            )

        # Check for HTTP errors
        if response.status_code != 200:
            error_detail = _parse_error(response)
            logger.error(
                f"OpenRouter API error: {response.status_code} — {error_detail}"
            )
            raise OpenRouterError(error_detail, status_code=response.status_code)

        # Parse successful response
        data = response.json()
        return _extract_content(data)

    except httpx.TimeoutException:
        logger.error("OpenRouter API timeout after 30 seconds")
        raise OpenRouterError(
            "AI service timed out. Please try again.",
            status_code=504,
        )
    except httpx.RequestError as e:
        logger.error(f"OpenRouter connection error: {e}")
        raise OpenRouterError(
            "Unable to reach AI service. Please try again later.",
            status_code=503,
        )


async def call_llm_with_context(
    system_prompt: str,
    user_message: str,
    context: str,
    temperature: float = 0.2,
    max_tokens: int = 1000,
) -> str:
    """
    Enhanced LLM call with additional context (e.g., query results).
    Context is appended to the user message for answer generation.

    Args:
        system_prompt: System instructions
        user_message: The original user question
        context: Additional data (SQL results, etc.)
        temperature: Randomness control
        max_tokens: Max response length

    Returns:
        The LLM's text response
    """
    combined_message = f"{user_message}\n\nContext data:\n{context}"
    return await call_llm(
        system_prompt=system_prompt,
        user_message=combined_message,
        temperature=temperature,
        max_tokens=max_tokens,
    )


def _extract_content(data: dict) -> str:
    """Extract the text content from OpenRouter's response format."""
    try:
        choices = data.get("choices", [])
        if not choices:
            raise OpenRouterError("No response generated by the AI model.")

        message = choices[0].get("message", {})
        content = message.get("content", "").strip()

        if not content:
            raise OpenRouterError("AI model returned an empty response.")

        return content

    except (KeyError, IndexError) as e:
        logger.error(f"Failed to parse OpenRouter response: {e}")
        raise OpenRouterError("Unexpected response format from AI service.")


def _parse_error(response: httpx.Response) -> str:
    """Parse error details from a failed OpenRouter response."""
    try:
        data = response.json()
        error = data.get("error", {})
        if isinstance(error, dict):
            return error.get("message", f"HTTP {response.status_code}")
        return str(error)
    except Exception:
        return f"HTTP {response.status_code}: {response.text[:200]}"
